name: Playwright Tests
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

permissions:
  packages: write

jobs:
  playwright:
    name: 'Acceptance tests'
    runs-on: ubuntu-latest\
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    env:
      APP_URL: http://shopware:8000
    services:
      # Label used to access the service container
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
        ports:
          - "3306:3306"
      shopware:
        image: ghcr.io/${{ github.repository }}/ci-e2e:${{ github.run_id }}
        env:
          APP_ENV: prod
          SHOPWARE_HTTP_CACHE_ENABLED: 0
          SHOPWARE_DISABLE_UPDATE_CHECK: "true"
          PROJECT_ROOT: /var/www/html
          DATABASE_URL: mysql://root:root@database:3306/root
          DATABASE_HOST: database
          APP_SECRET: def00000bc5acb32b54ff8ee130270586eec0e878f7337dc7a837acc31d3ff00f93a56b595448b4b29664847dd51991b3314ff65aeeeb761a133b0ec0e070433bff08e48
          BLUE_GREEN_DEPLOYMENT: 1
          APP_URL: http://shopware:8000
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "shopware/shopware"
          ref: trunk
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: tests/acceptance
        run: npm ci
      - name: Run your tests
        working-directory: tests/acceptance
        run: npx playwright test --project=Platform
        env:
          HOME: /root