name: Manual job to test cross workflow download
on:
  workflow_dispatch:

jobs:
  find:
    runs-on: ubuntu-latest
    steps:
        - name: Download artifact
          id: download-artifact
          uses: dawidd6/action-download-artifact@v3
          with:
            workflow: build.yml
            name: ${{ github.event.repository.name }}.zip
        - name: Display structure of downloaded files
          run: ls -R
            
